import { norm } from "./shared";
import type { Arch } from "./types";

// Curated deck. `params` = flagship / most-cited variant, in millions.
// Sources of record: original paper + model card. See scripts/enrich.ts for the
// pipeline that re-verifies year / org / params against arXiv + HF + Wikidata.
export const ARCHITECTURES: Arch[] = [
  // ── Foundations ───────────────────────────────────────────────────────────
  { name: "Perceptron", year: 1958, modality: ["Tabular"], mechanism: "MLP", paradigm: "Supervised", org: "Cornell Aeronautical Lab", params: 0.0005, weights: "Open", parents: [], blurb: "Rosenblatt's single-layer linear classifier — the first trainable neural net.", tier: 1 },
  { name: "Neocognitron", year: 1980, modality: ["Vision"], mechanism: "Convolution", paradigm: "Reconstruction", org: "NHK Labs", params: 0.01, weights: "Closed", parents: ["Perceptron"], blurb: "Fukushima's hierarchical S/C-cell model — the ancestor of every CNN.", tier: 2 },
  { name: "Hopfield Network", year: 1982, modality: ["Tabular"], mechanism: "Energy-based", paradigm: "Reconstruction", org: "Caltech", params: 0.001, weights: "Open", parents: [], blurb: "Associative memory as an energy landscape. Nobel Prize, 2024.", tier: 1 },
  { name: "Boltzmann Machine", year: 1985, modality: ["Tabular"], mechanism: "Energy-based", paradigm: "Reconstruction", org: "CMU / Johns Hopkins", params: 0.001, weights: "Open", parents: ["Hopfield Network"], blurb: "Stochastic Hopfield net with hidden units, trained by contrastive divergence.", tier: 2 },
  { name: "Elman RNN", aliases: ["Simple Recurrent Network"], year: 1990, modality: ["Language"], mechanism: "Recurrence", paradigm: "Supervised", org: "UC San Diego", params: 0.001, weights: "Open", parents: [], blurb: "Context units carrying hidden state across timesteps. 'Finding Structure in Time'.", tier: 2 },
  { name: "SVM", aliases: ["Support Vector Machine"], year: 1995, modality: ["Tabular"], mechanism: "Kernel machine", paradigm: "Supervised", org: "AT&T Bell Labs", params: null, weights: "Open", parents: [], blurb: "Max-margin classifier with the kernel trick. Ruled ML for a decade.", tier: 1 },
  { name: "LSTM", year: 1997, modality: ["Language"], mechanism: "Recurrence", paradigm: "Supervised", org: "TU München / IDSIA", params: 0.01, weights: "Open", parents: ["Elman RNN"], blurb: "Gated cells with a constant error carousel — solved vanishing gradients.", tier: 1 },
  { name: "LeNet-5", year: 1998, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "AT&T Bell Labs", params: 0.06, weights: "Open", parents: ["Neocognitron"], blurb: "LeCun's digit reader — conv + pool + FC, the template for 25 years.", tier: 1 },
  { name: "Random Forest", year: 2001, modality: ["Tabular"], mechanism: "Tree ensemble", paradigm: "Supervised", org: "UC Berkeley", params: null, weights: "Open", parents: [], blurb: "Bagged decision trees with feature subsampling. Breiman, 2001.", tier: 1 },
  { name: "Deep Belief Network", year: 2006, modality: ["Vision"], mechanism: "Energy-based", paradigm: "Reconstruction", org: "University of Toronto", params: 1.6, weights: "Open", parents: ["Boltzmann Machine"], blurb: "Stacked RBMs with greedy layerwise pretraining — kicked off 'deep learning'.", tier: 2 },
  { name: "Denoising Autoencoder", year: 2008, modality: ["Vision"], mechanism: "MLP", paradigm: "Reconstruction", org: "Université de Montréal", params: 1, weights: "Open", parents: [], blurb: "Corrupt the input, reconstruct the original. Self-supervision, 2008 edition.", tier: 2 },

  // ── The ImageNet decade ───────────────────────────────────────────────────
  { name: "AlexNet", year: 2012, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "University of Toronto", params: 60, weights: "Open", parents: ["LeNet-5"], blurb: "ReLU + dropout + two GTX 580s. Won ImageNet 2012 by 10 points.", tier: 1 },
  { name: "Word2Vec", year: 2013, modality: ["Language"], mechanism: "MLP", paradigm: "Contrastive", org: "Google", params: 3, weights: "Open", parents: [], blurb: "Skip-gram with negative sampling. king − man + woman = queen.", tier: 1 },
  { name: "VGG-16", aliases: ["VGG"], year: 2014, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "University of Oxford", params: 138, weights: "Open", parents: ["AlexNet"], blurb: "Nothing but stacked 3×3 convs. Depth is all you need (in 2014).", tier: 1 },
  { name: "GoogLeNet", aliases: ["Inception", "Inception v1"], year: 2014, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "Google", params: 6.8, weights: "Open", parents: ["AlexNet"], blurb: "Inception modules: parallel multi-scale convs, 12× fewer params than VGG.", tier: 1 },
  { name: "R-CNN", year: 2014, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "UC Berkeley", params: 60, weights: "Open", parents: ["AlexNet"], blurb: "Region proposals + a CNN per region. Slow, and it changed detection anyway.", tier: 1 },
  { name: "GAN", aliases: ["Generative Adversarial Network"], year: 2014, modality: ["Vision"], mechanism: "MLP", paradigm: "Adversarial", org: "Université de Montréal", params: 1.5, weights: "Open", parents: [], blurb: "Generator vs discriminator, a minimax game. Goodfellow, 2014.", tier: 1 },
  { name: "VAE", aliases: ["Variational Autoencoder"], year: 2014, modality: ["Vision"], mechanism: "MLP", paradigm: "Variational", org: "Universiteit van Amsterdam", params: 1, weights: "Open", parents: ["Denoising Autoencoder"], blurb: "Reparameterisation trick + ELBO. Latent variables you can backprop through.", tier: 1 },
  { name: "Seq2Seq", aliases: ["Sequence to Sequence"], year: 2014, modality: ["Language"], mechanism: "Recurrence", paradigm: "Supervised", org: "Google", params: 384, weights: "Closed", parents: ["LSTM"], blurb: "Encoder LSTM to a thought vector, decoder LSTM out. 384M params in 2014.", tier: 1 },
  { name: "GRU", year: 2014, modality: ["Language"], mechanism: "Recurrence", paradigm: "Supervised", org: "Université de Montréal", params: 0.5, weights: "Open", parents: ["LSTM"], blurb: "LSTM with two gates instead of three. Cheaper, usually just as good.", tier: 1 },
  { name: "GloVe", year: 2014, modality: ["Language"], mechanism: "MLP", paradigm: "Reconstruction", org: "Stanford University", params: 6, weights: "Open", parents: ["Word2Vec"], blurb: "Global co-occurrence matrix factorisation for word vectors.", tier: 1 },
  { name: "Deep Speech", year: 2014, modality: ["Audio", "Language"], mechanism: "Recurrence", paradigm: "Supervised", org: "Baidu Research", params: 38, weights: "Open", parents: ["LSTM"], blurb: "End-to-end CTC speech recognition — no phonemes, no HMMs.", tier: 1 },
  { name: "Neural Turing Machine", year: 2014, modality: ["Language"], mechanism: "Hybrid", paradigm: "Supervised", org: "DeepMind", params: 0.02, weights: "Closed", parents: ["LSTM"], blurb: "An RNN controller with a differentiable external memory tape.", tier: 1 },
  { name: "Bahdanau Attention", aliases: ["RNNSearch", "Additive attention"], year: 2015, modality: ["Language"], mechanism: "Recurrence", paradigm: "Supervised", org: "Université de Montréal", params: 100, weights: "Open", parents: ["Seq2Seq"], blurb: "Soft alignment over encoder states. The first attention mechanism.", tier: 1 },
  { name: "ResNet-50", aliases: ["ResNet"], paper: "Deep Residual Learning for Image Recognition", year: 2015, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "Microsoft Research Asia", params: 25.6, weights: "Open", parents: ["VGG-16"], blurb: "Identity skip connections. Suddenly 152 layers trained fine.", tier: 1 },
  { name: "U-Net", year: 2015, modality: ["Vision", "Biology"], mechanism: "Convolution", paradigm: "Supervised", org: "University of Freiburg", params: 31, weights: "Open", parents: ["LeNet-5"], blurb: "Contracting/expanding path with skip connections. Now every diffusion backbone.", tier: 1 },
  { name: "Faster R-CNN", year: 2015, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "Microsoft Research", params: 60, weights: "Open", parents: ["R-CNN"], blurb: "Region Proposal Network shares conv features — detection at 5 fps.", tier: 1 },
  { name: "Highway Networks", year: 2015, modality: ["Vision"], mechanism: "MLP", paradigm: "Supervised", org: "IDSIA", params: 2.3, weights: "Open", parents: ["LSTM"], blurb: "LSTM-style gates applied depthwise. Residual connections, months early.", tier: 2 },
  { name: "DQN", aliases: ["Deep Q-Network"], year: 2015, modality: ["Control", "Vision"], mechanism: "Convolution", paradigm: "Reinforcement learning", org: "DeepMind", params: 1.7, weights: "Closed", parents: ["AlexNet"], blurb: "Q-learning + replay buffer + target network. Human-level Atari.", tier: 1 },
  { name: "YOLO", year: 2016, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "University of Washington", params: 45, weights: "Open", parents: ["GoogLeNet"], blurb: "One forward pass, a grid of boxes. Real-time detection.", tier: 1 },
  { name: "SqueezeNet", year: 2016, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "UC Berkeley / Stanford", params: 1.2, weights: "Open", parents: ["AlexNet"], blurb: "AlexNet accuracy at 1/50th the parameters via fire modules.", tier: 1 },
  { name: "DenseNet", year: 2016, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "Cornell / Tsinghua / FAIR", params: 8, weights: "Open", parents: ["ResNet-50"], blurb: "Every layer connected to every later layer. Feature reuse taken literally.", tier: 1 },
  { name: "XGBoost", year: 2016, modality: ["Tabular"], mechanism: "Tree ensemble", paradigm: "Supervised", org: "University of Washington", params: null, weights: "Open", parents: ["Random Forest"], blurb: "Regularised gradient boosting. Still wins Kaggle tabular in 2026.", tier: 1 },
  { name: "DCGAN", year: 2016, modality: ["Vision"], mechanism: "Convolution", paradigm: "Adversarial", org: "Indico / Facebook AI Research", params: 12, weights: "Open", parents: ["GAN"], blurb: "The architectural recipe that made GANs actually train.", tier: 1 },
  { name: "WaveNet", year: 2016, modality: ["Audio"], mechanism: "Convolution", paradigm: "Autoregressive", org: "DeepMind", params: 5, weights: "Closed", parents: ["PixelCNN"], blurb: "Dilated causal convolutions over raw 16 kHz samples.", tier: 1 },
  { name: "PixelCNN", aliases: ["PixelRNN"], year: 2016, modality: ["Vision"], mechanism: "Convolution", paradigm: "Autoregressive", org: "DeepMind", params: 3, weights: "Closed", parents: [], blurb: "Model an image as p(pixel | all previous pixels). Masked convs.", tier: 2 },
  { name: "AlphaGo", year: 2016, modality: ["Control"], mechanism: "Convolution", paradigm: "Reinforcement learning", org: "DeepMind", params: 30, weights: "Closed", parents: ["DQN"], blurb: "Policy + value nets guiding MCTS. Beat Lee Sedol 4–1.", tier: 1 },
  { name: "Differentiable Neural Computer", year: 2016, modality: ["Language"], mechanism: "Hybrid", paradigm: "Supervised", org: "DeepMind", params: 1, weights: "Closed", parents: ["Neural Turing Machine"], blurb: "NTM with dynamic memory allocation and temporal links.", tier: 2 },

  // ── The Transformer era ───────────────────────────────────────────────────
  { name: "Transformer", aliases: ["Attention Is All You Need", "Vanilla Transformer"], paper: "Attention Is All You Need", year: 2017, modality: ["Language"], mechanism: "Self-attention", paradigm: "Supervised", org: "Google", params: 213, weights: "Open", parents: ["Bahdanau Attention"], blurb: "Multi-head self-attention, no recurrence. The whole field pivots here.", tier: 1 },
  { name: "MobileNet", year: 2017, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "Google", params: 4.2, weights: "Open", parents: ["GoogLeNet"], blurb: "Depthwise separable convs for phones.", tier: 1 },
  { name: "Mask R-CNN", year: 2017, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "Facebook AI Research", params: 44, weights: "Open", parents: ["Faster R-CNN"], blurb: "Adds a per-RoI mask branch. Instance segmentation, solved-ish.", tier: 1 },
  { name: "CycleGAN", year: 2017, modality: ["Vision"], mechanism: "Convolution", paradigm: "Adversarial", org: "UC Berkeley", params: 11, weights: "Open", parents: ["DCGAN"], blurb: "Unpaired image translation via cycle-consistency loss. Horses to zebras.", tier: 1 },
  { name: "VQ-VAE", year: 2017, modality: ["Vision", "Audio"], mechanism: "Convolution", paradigm: "Reconstruction", org: "DeepMind", params: 20, weights: "Closed", parents: ["VAE"], blurb: "Discrete latent codes via vector quantisation. The tokeniser behind DALL·E.", tier: 1 },
  { name: "Capsule Network", aliases: ["CapsNet"], year: 2017, modality: ["Vision"], mechanism: "Hybrid", paradigm: "Supervised", org: "Google Brain", params: 8, weights: "Open", parents: ["LeNet-5"], blurb: "Hinton's pose-aware capsules with dynamic routing. Never quite scaled.", tier: 1 },
  { name: "GCN", aliases: ["Graph Convolutional Network"], year: 2017, modality: ["Graph"], mechanism: "Graph message passing", paradigm: "Supervised", org: "Universiteit van Amsterdam", params: 0.02, weights: "Open", parents: [], blurb: "Kipf & Welling's spectral-approximation layer. Two lines of matrix algebra.", tier: 1 },
  { name: "GraphSAGE", year: 2017, modality: ["Graph"], mechanism: "Graph message passing", paradigm: "Supervised", org: "Stanford University", params: 0.03, weights: "Open", parents: ["GCN"], blurb: "Sample-and-aggregate neighbourhoods — inductive graph learning.", tier: 1 },
  { name: "AlphaZero", year: 2017, modality: ["Control"], mechanism: "Convolution", paradigm: "Reinforcement learning", org: "DeepMind", params: 46, weights: "Closed", parents: ["AlphaGo"], blurb: "Self-play from zero, one algorithm for Go, chess and shogi.", tier: 1 },
  { name: "GAT", aliases: ["Graph Attention Network"], year: 2018, modality: ["Graph"], mechanism: "Graph message passing", paradigm: "Supervised", org: "Mila / Université de Montréal", params: 0.03, weights: "Open", parents: ["GCN", "Transformer"], blurb: "Attention over graph neighbours instead of fixed averaging.", tier: 1 },
  { name: "BERT", paper: "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", year: 2018, modality: ["Language"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Google", params: 340, weights: "Open", parents: ["Transformer"], blurb: "Bidirectional encoder, masked-token pretraining. Owned NLP for three years.", tier: 1 },
  { name: "GPT-1", aliases: ["GPT"], year: 2018, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "OpenAI", params: 117, weights: "Open", parents: ["Transformer"], blurb: "Decoder-only, generative pretraining, then task fine-tuning.", tier: 1 },
  { name: "ELMo", year: 2018, modality: ["Language"], mechanism: "Recurrence", paradigm: "Autoregressive", org: "Allen Institute for AI", params: 94, weights: "Open", parents: ["LSTM"], blurb: "Deep bidirectional LSTM embeddings that finally beat static vectors.", tier: 1 },
  { name: "BigGAN", year: 2018, modality: ["Vision"], mechanism: "Convolution", paradigm: "Adversarial", org: "DeepMind", params: 158, weights: "Open", parents: ["DCGAN"], blurb: "Scale the batch, scale the model, truncate the noise. Photoreal ImageNet.", tier: 1 },
  { name: "Glow", year: 2018, modality: ["Vision"], mechanism: "Convolution", paradigm: "Normalizing flow", org: "OpenAI", params: 200, weights: "Open", parents: ["VAE"], blurb: "Invertible 1×1 convolutions — exact likelihoods, exact inversion.", tier: 2 },
  { name: "StyleGAN", year: 2019, modality: ["Vision"], mechanism: "Convolution", paradigm: "Adversarial", org: "NVIDIA", params: 26, weights: "Open", parents: ["BigGAN"], blurb: "Style-modulated generator. thispersondoesnotexist.com.", tier: 1 },
  { name: "GPT-2", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "OpenAI", params: 1500, weights: "Partial", parents: ["GPT-1"], blurb: "'Too dangerous to release.' Staged rollout, then full weights.", tier: 1 },
  { name: "RoBERTa", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Facebook AI Research", params: 355, weights: "Open", parents: ["BERT"], blurb: "BERT, but trained properly: more data, longer, no NSP.", tier: 1 },
  { name: "T5", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Google", params: 11000, weights: "Open", parents: ["Transformer"], blurb: "Every NLP task as text-to-text. Also gave us C4.", tier: 1 },
  { name: "XLNet", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "CMU / Google Brain", params: 340, weights: "Open", parents: ["Transformer-XL", "BERT"], blurb: "Permutation language modelling — autoregressive but bidirectional.", tier: 1 },
  { name: "Transformer-XL", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "CMU / Google Brain", params: 257, weights: "Open", parents: ["Transformer"], blurb: "Segment recurrence + relative positions for long context.", tier: 1, until: 268 /* identical row to XLNet, so it can't be told apart as an answer */ },
  { name: "DistilBERT", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Self-distillation", org: "Hugging Face", params: 66, weights: "Open", parents: ["BERT"], blurb: "40% smaller, 60% faster, 97% of BERT. Distillation goes mainstream.", tier: 1 },
  { name: "ALBERT", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Google", params: 235, weights: "Open", parents: ["BERT"], blurb: "Factorised embeddings and cross-layer parameter sharing.", tier: 1 },
  { name: "BART", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Reconstruction", org: "Facebook AI Research", params: 400, weights: "Open", parents: ["BERT", "GPT-1"], blurb: "Denoising seq2seq — corrupt arbitrarily, reconstruct the original text.", tier: 1 },
  { name: "EfficientNet", year: 2019, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "Google", params: 66, weights: "Open", parents: ["MobileNet"], blurb: "Compound scaling of depth, width and resolution, found by NAS.", tier: 1 },
  { name: "Megatron-LM", year: 2019, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "NVIDIA", params: 8300, weights: "Open", parents: ["GPT-2"], blurb: "Tensor-parallel training. The plumbing that made 100B+ possible.", tier: 1 },

  // ── Scaling laws and self-supervision ─────────────────────────────────────
  { name: "GPT-3", year: 2020, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "OpenAI", params: 175000, weights: "Closed", parents: ["GPT-2"], blurb: "175B params, few-shot prompting, no fine-tuning required.", tier: 1 },
  { name: "Vision Transformer", aliases: ["ViT"], year: 2020, modality: ["Vision"], mechanism: "Self-attention", paradigm: "Supervised", org: "Google", params: 86, weights: "Open", parents: ["Transformer"], blurb: "16×16 patches as tokens. An image is worth 16×16 words.", tier: 1 },
  { name: "DETR", year: 2020, modality: ["Vision"], mechanism: "Self-attention", paradigm: "Supervised", org: "Facebook AI Research", params: 41, weights: "Open", parents: ["Transformer", "Faster R-CNN"], blurb: "Set prediction with bipartite matching — no anchors, no NMS.", tier: 1 },
  { name: "DDPM", aliases: ["Denoising Diffusion Probabilistic Models"], year: 2020, modality: ["Vision"], mechanism: "Convolution", paradigm: "Diffusion", org: "UC Berkeley", params: 36, weights: "Open", parents: ["U-Net", "VAE"], blurb: "Learn to reverse a noising Markov chain. Made diffusion competitive.", tier: 1 },
  { name: "SimCLR", year: 2020, modality: ["Vision"], mechanism: "Convolution", paradigm: "Contrastive", org: "Google", params: 24, weights: "Open", parents: ["ResNet-50"], blurb: "Strong augmentations + NT-Xent loss + a big batch. That's the whole trick.", tier: 1 },
  { name: "MoCo", year: 2020, modality: ["Vision"], mechanism: "Convolution", paradigm: "Contrastive", org: "Facebook AI Research", params: 24, weights: "Open", parents: ["ResNet-50"], blurb: "Momentum encoder + queue, so contrastive learning stops needing huge batches.", tier: 1 },
  { name: "BYOL", year: 2020, modality: ["Vision"], mechanism: "Convolution", paradigm: "Self-distillation", org: "DeepMind", params: 24, weights: "Open", parents: ["MoCo"], blurb: "Self-supervised learning with no negative pairs at all. Shouldn't work. Does.", tier: 1 },
  { name: "wav2vec 2.0", year: 2020, modality: ["Audio"], mechanism: "Self-attention", paradigm: "Contrastive", org: "Facebook AI Research", params: 317, weights: "Open", parents: ["Transformer"], blurb: "Masked contrastive pretraining on raw audio. 10 minutes of labels is enough.", tier: 1 },
  { name: "NeRF", year: 2020, modality: ["Vision"], mechanism: "MLP", paradigm: "Supervised", org: "UC Berkeley", params: 0.6, weights: "Open", parents: [], blurb: "A tiny MLP that *is* the scene. Volume rendering by ray marching.", tier: 1 },
  { name: "Longformer", year: 2020, modality: ["Language"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Allen Institute for AI", params: 149, weights: "Open", parents: ["RoBERTa"], blurb: "Sliding-window + global attention, linear in sequence length.", tier: 1 },
  { name: "Reformer", year: 2020, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Google", params: 213, weights: "Open", parents: ["Transformer"], blurb: "LSH attention and reversible layers. 64K context on one accelerator.", tier: 1 },
  { name: "GShard", year: 2020, modality: ["Language"], mechanism: "Self-attention", paradigm: "Supervised", org: "Google", params: 600000, weights: "Closed", parents: ["Transformer"], blurb: "600B sparse MoE for translation. The first trillion-scale sharding story.", tier: 1 },
  { name: "MuZero", year: 2020, modality: ["Control"], mechanism: "Convolution", paradigm: "Reinforcement learning", org: "DeepMind", params: 40, weights: "Closed", parents: ["AlphaZero"], blurb: "Planning in a learned latent model — no rules given.", tier: 1 },

  // ── 2021: foundation models ───────────────────────────────────────────────
  { name: "CLIP", year: 2021, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Contrastive", org: "OpenAI", params: 428, weights: "Open", parents: ["Transformer", "Vision Transformer"], blurb: "400M image–text pairs, one contrastive objective. Zero-shot vision.", tier: 1 },
  { name: "DALL·E", aliases: ["DALL-E"], year: 2021, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "OpenAI", params: 12000, weights: "Closed", parents: ["GPT-3", "VQ-VAE"], blurb: "Text and image tokens in one autoregressive stream.", tier: 1 },
  { name: "Swin Transformer", year: 2021, modality: ["Vision"], mechanism: "Self-attention", paradigm: "Supervised", org: "Microsoft Research Asia", params: 88, weights: "Open", parents: ["Vision Transformer"], blurb: "Shifted local windows restore the CNN's hierarchy inside a transformer.", tier: 1 },
  { name: "MAE", aliases: ["Masked Autoencoder"], year: 2021, modality: ["Vision"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Facebook AI Research", params: 632, weights: "Open", parents: ["Vision Transformer", "BERT"], blurb: "Mask 75% of patches, reconstruct pixels. BERT for images, finally.", tier: 1 },
  { name: "MLP-Mixer", year: 2021, modality: ["Vision"], mechanism: "MLP", paradigm: "Supervised", org: "Google", params: 59, weights: "Open", parents: ["Vision Transformer"], blurb: "Drop attention entirely; mix tokens and channels with MLPs. Still works.", tier: 1 },
  { name: "Perceiver", year: 2021, modality: ["Vision", "Audio"], mechanism: "Self-attention", paradigm: "Supervised", org: "DeepMind", params: 45, weights: "Open", parents: ["Transformer"], blurb: "Cross-attend a huge input into a small latent array. Any modality, one model.", tier: 1 },
  { name: "S4", aliases: ["Structured State Space"], year: 2021, modality: ["Audio", "Language"], mechanism: "State space", paradigm: "Supervised", org: "Stanford University", params: 7, weights: "Open", parents: [], blurb: "HiPPO-initialised SSM that finally cracked Long Range Arena.", tier: 1 },
  { name: "Switch Transformer", year: 2021, modality: ["Language"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Google", params: 1600000, weights: "Closed", parents: ["T5", "GShard"], blurb: "Top-1 routing to 2048 experts. 1.6 trillion params, constant FLOPs.", tier: 1 },
  { name: "Gopher", year: 2021, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "DeepMind", params: 280000, weights: "Closed", parents: ["GPT-3"], blurb: "280B params and a very careful 152-task evaluation.", tier: 1 },
  { name: "AlphaFold 2", aliases: ["AlphaFold"], year: 2021, modality: ["Biology"], mechanism: "Self-attention", paradigm: "Supervised", org: "DeepMind", params: 93, weights: "Open", parents: ["Transformer"], blurb: "Evoformer + structure module. CASP14 was effectively over.", tier: 1 },
  { name: "HuBERT", year: 2021, modality: ["Audio"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Facebook AI Research", params: 964, weights: "Open", parents: ["wav2vec 2.0", "BERT"], blurb: "Masked prediction of offline-clustered units. BERT for speech.", tier: 1 },
  { name: "Decision Transformer", year: 2021, modality: ["Control"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "UC Berkeley", params: 200, weights: "Open", parents: ["GPT-2"], blurb: "RL as conditional sequence modelling on return-to-go.", tier: 1 },
  { name: "Codex", year: 2021, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "OpenAI", params: 12000, weights: "Closed", parents: ["GPT-3"], blurb: "GPT-3 fine-tuned on GitHub. Became Copilot.", tier: 1 },

  // ── 2022 ──────────────────────────────────────────────────────────────────
  { name: "Stable Diffusion", aliases: ["Latent Diffusion", "LDM"], year: 2022, modality: ["Vision", "Language"], mechanism: "Convolution", paradigm: "Diffusion", org: "CompVis / Stability AI", params: 860, weights: "Open", parents: ["DDPM", "CLIP", "VQ-VAE"], blurb: "Diffusion in VAE latent space. Open weights broke image gen wide open.", tier: 1 },
  { name: "DALL·E 2", aliases: ["unCLIP"], year: 2022, modality: ["Vision", "Language"], mechanism: "Convolution", paradigm: "Diffusion", org: "OpenAI", params: 3500, weights: "Closed", parents: ["CLIP", "DDPM"], blurb: "CLIP-latent prior plus a diffusion decoder.", tier: 1 },
  { name: "Imagen", year: 2022, modality: ["Vision", "Language"], mechanism: "Convolution", paradigm: "Diffusion", org: "Google", params: 3000, weights: "Closed", parents: ["DDPM", "T5"], blurb: "A frozen T5 text encoder does most of the work. Cascaded upsamplers.", tier: 1 },
  { name: "DiT", aliases: ["Diffusion Transformer"], year: 2022, modality: ["Vision"], mechanism: "Self-attention", paradigm: "Diffusion", org: "UC Berkeley / NYU", params: 675, weights: "Open", parents: ["Vision Transformer", "DDPM"], blurb: "Replace the U-Net with a transformer. The backbone behind Sora.", tier: 1 },
  { name: "PaLM", year: 2022, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Google", params: 540000, weights: "Closed", parents: ["Transformer"], blurb: "540B dense params trained on 6144 TPU v4 chips via Pathways.", tier: 1 },
  { name: "Chinchilla", year: 2022, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "DeepMind", params: 70000, weights: "Closed", parents: ["Gopher"], blurb: "Compute-optimal scaling: ~20 tokens per parameter. Everyone was undertrained.", tier: 1 },
  { name: "InstructGPT", year: 2022, modality: ["Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "OpenAI", params: 175000, weights: "Closed", parents: ["GPT-3"], blurb: "SFT then RLHF. The alignment recipe that made ChatGPT possible.", tier: 1 },
  { name: "Whisper", year: 2022, modality: ["Audio", "Language"], mechanism: "Self-attention", paradigm: "Supervised", org: "OpenAI", params: 1550, weights: "Open", parents: ["Transformer"], blurb: "680k hours of weakly-labelled audio, plain supervised seq2seq.", tier: 1 },
  { name: "Flamingo", year: 2022, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "DeepMind", params: 80000, weights: "Closed", parents: ["Chinchilla", "CLIP"], blurb: "Gated cross-attention bolting a vision encoder onto a frozen LM.", tier: 1 },
  { name: "BLOOM", year: 2022, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "BigScience", params: 176000, weights: "Open", parents: ["GPT-3"], blurb: "1000 researchers, 46 languages, fully open 176B. Trained on Jean Zay.", tier: 1 },
  { name: "OPT", year: 2022, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Meta AI", params: 175000, weights: "Partial", parents: ["GPT-3"], blurb: "A GPT-3 replication released with its logbook. Research-only licence.", tier: 1 },
  { name: "GPT-NeoX", year: 2022, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "EleutherAI", params: 20000, weights: "Open", parents: ["GPT-3"], blurb: "Grassroots 20B trained on the Pile. Rotary embeddings, open everything.", tier: 1 },
  { name: "ConvNeXt", year: 2022, modality: ["Vision"], mechanism: "Convolution", paradigm: "Supervised", org: "Facebook AI Research", params: 89, weights: "Open", parents: ["ResNet-50", "Swin Transformer"], blurb: "Modernise a ResNet with ViT design choices; it wins again.", tier: 1 },
  { name: "ESM-2", year: 2022, modality: ["Biology"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Meta AI", params: 15000, weights: "Open", parents: ["BERT"], blurb: "A 15B masked language model over protein sequences. Structure falls out.", tier: 1 },

  // ── 2023 ──────────────────────────────────────────────────────────────────
  { name: "GPT-4", year: 2023, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "OpenAI", params: null, weights: "Closed", parents: ["GPT-3", "InstructGPT"], blurb: "Multimodal, bar-exam-passing, and the technical report says nothing.", tier: 1 },
  { name: "LLaMA", aliases: ["LLaMA 1"], year: 2023, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Meta AI", params: 65000, weights: "Partial", parents: ["Chinchilla"], blurb: "Chinchilla-style training on public data. Leaked, and the ecosystem exploded.", tier: 1 },
  { name: "Llama 2", year: 2023, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Meta AI", params: 70000, weights: "Open", parents: ["LLaMA"], blurb: "Open weights, commercial licence, GQA and a proper RLHF pipeline.", tier: 1 },
  { name: "Mistral 7B", year: 2023, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Mistral AI", params: 7000, weights: "Open", parents: ["Llama 2"], blurb: "Sliding-window + GQA. Beat every 13B model at 7B.", tier: 1 },
  { name: "Mixtral 8x7B", year: 2023, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Mistral AI", params: 46700, weights: "Open", parents: ["Mistral 7B", "Switch Transformer"], blurb: "Sparse MoE, 8 experts, 2 active. 47B stored, 13B used.", tier: 1 },
  { name: "Mamba", paper: "Mamba: Linear-Time Sequence Modeling with Selective State Spaces", year: 2023, modality: ["Language"], mechanism: "State space", paradigm: "Autoregressive", org: "CMU / Princeton", params: 2800, weights: "Open", parents: ["S4"], blurb: "Selective SSM with a hardware-aware scan. Linear time, no attention.", tier: 1 },
  { name: "SAM", aliases: ["Segment Anything"], year: 2023, modality: ["Vision"], mechanism: "Self-attention", paradigm: "Supervised", org: "Meta AI", params: 636, weights: "Open", parents: ["MAE", "Vision Transformer"], blurb: "Promptable segmentation trained on 1.1B masks.", tier: 1 },
  { name: "DINOv2", year: 2023, modality: ["Vision"], mechanism: "Self-attention", paradigm: "Self-distillation", org: "Meta AI", params: 1100, weights: "Open", parents: ["BYOL", "Vision Transformer"], blurb: "Self-supervised features so good you can freeze them and skip fine-tuning.", tier: 1 },
  { name: "Claude", year: 2023, modality: ["Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "Anthropic", params: null, weights: "Closed", parents: ["Transformer"], blurb: "Constitutional AI: RL from AI feedback against a written constitution.", tier: 1 },
  { name: "Gemini", year: 2023, modality: ["Vision", "Language", "Audio", "Video"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Google DeepMind", params: null, weights: "Closed", parents: ["PaLM"], blurb: "Natively multimodal from pretraining, not a bolted-on encoder.", tier: 1 },
  { name: "Falcon", year: 2023, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Technology Innovation Institute", params: 180000, weights: "Open", parents: ["GPT-3"], blurb: "180B trained on RefinedWeb — filtered web data beat curated corpora.", tier: 1 },
  { name: "Qwen", year: 2023, modality: ["Language", "Vision"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Alibaba", params: 72000, weights: "Open", parents: ["LLaMA"], blurb: "Alibaba's open series; became the default base model across China.", tier: 1 },
  { name: "Phi-2", year: 2023, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Microsoft Research", params: 2700, weights: "Open", parents: ["Transformer"], blurb: "Textbook-quality synthetic data. 2.7B punching at 25B.", tier: 1 },
  { name: "RWKV", year: 2023, modality: ["Language"], mechanism: "Hybrid", paradigm: "Autoregressive", org: "RWKV Foundation", params: 14000, weights: "Open", parents: ["LSTM", "Transformer"], blurb: "Trains like a transformer, runs like an RNN. Community-built.", tier: 1 },
  { name: "RetNet", year: 2023, modality: ["Language"], mechanism: "Hybrid", paradigm: "Autoregressive", org: "Microsoft Research", params: 6700, weights: "Open", parents: ["Transformer"], blurb: "Retention: parallel training, recurrent O(1) inference.", tier: 1 },
  { name: "Hyena", year: 2023, modality: ["Language"], mechanism: "Convolution", paradigm: "Autoregressive", org: "Stanford University", params: 1300, weights: "Open", parents: ["S4"], blurb: "Long implicit convolutions + gating as a subquadratic attention drop-in.", tier: 1 },
  { name: "GraphCast", year: 2023, modality: ["Weather", "Graph"], mechanism: "Graph message passing", paradigm: "Supervised", org: "Google DeepMind", params: 36.7, weights: "Open", parents: ["GCN"], blurb: "10-day global forecasts in 60 seconds, beating the ECMWF gold standard.", tier: 1 },

  // ── 2024–2025 ─────────────────────────────────────────────────────────────
  { name: "Llama 3", year: 2024, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Meta AI", params: 405000, weights: "Open", parents: ["Llama 2"], blurb: "405B dense, 15T tokens. The largest openly released model of its day.", tier: 1 },
  { name: "Sora", year: 2024, modality: ["Video", "Language"], mechanism: "Self-attention", paradigm: "Diffusion", org: "OpenAI", params: null, weights: "Closed", parents: ["DiT"], blurb: "Spacetime patches through a diffusion transformer. Minute-long video.", tier: 1 },
  { name: "Gemma", year: 2024, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Google DeepMind", params: 7000, weights: "Open", parents: ["Gemini"], blurb: "Gemini's research lineage, shrunk and released with open weights.", tier: 1 },
  { name: "Jamba", year: 2024, modality: ["Language"], mechanism: "Hybrid", paradigm: "Autoregressive", org: "AI21 Labs", params: 52000, weights: "Open", parents: ["Mamba", "Mixtral 8x7B"], blurb: "Interleaved Mamba and attention blocks, plus MoE. 256K context.", tier: 1 },
  { name: "FLUX.1", aliases: ["Flux"], year: 2024, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Diffusion", org: "Black Forest Labs", params: 12000, weights: "Open", parents: ["Stable Diffusion", "DiT"], blurb: "12B rectified-flow transformer from the original Stable Diffusion team.", tier: 1 },
  { name: "DeepSeek-V3", year: 2024, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "DeepSeek", params: 671000, weights: "Open", parents: ["Mixtral 8x7B"], blurb: "671B MoE, 37B active, multi-head latent attention, ~$5.6M of compute.", tier: 1 },
  { name: "DeepSeek-R1", year: 2025, modality: ["Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "DeepSeek", params: 671000, weights: "Open", parents: ["DeepSeek-V3"], blurb: "Reasoning learned by pure RL with verifiable rewards. Open weights.", tier: 1 },

  // ── 2025–2026 ─────────────────────────────────────────────────────────────
  // Verified against model cards, papers and lab posts in Sept 2026. `from`
  // keeps them out of the daily rotation until a day that hadn't started yet.
  { name: "LLaDA", aliases: ["LLaDA 8B", "Large Language Diffusion Models"], year: 2025, modality: ["Language"], mechanism: "Self-attention", paradigm: "Diffusion", org: "Renmin University / Ant Group", params: 8000, weights: "Open", parents: ["Llama 3", "DiT"], blurb: "8B masked-diffusion LM trained from scratch on 2.3T tokens; beats the reversal curse.", tier: 1, from: 269 },
  { name: "Evo 2", aliases: ["Evo2"], year: 2025, modality: ["Biology"], mechanism: "Hybrid", paradigm: "Autoregressive", org: "Arc Institute / NVIDIA", params: 40000, weights: "Open", parents: ["Hyena", "ESM-2"], blurb: "40B DNA model, 9.3T base pairs from 128k+ species, 1M-nucleotide context.", tier: 1, from: 269 },
  { name: "Gemma 3", aliases: ["Gemma 3 27B"], year: 2025, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Google DeepMind", params: 27000, weights: "Open", parents: ["Gemma", "Gemini"], blurb: "27B open multimodal model for a single GPU: image input, 128K context, 140+ languages.", tier: 1, from: 269 },
  { name: "Llama 4", aliases: ["Llama 4 Maverick", "Llama 4 Scout"], year: 2025, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Meta AI", params: 400000, weights: "Open", parents: ["Llama 3", "Mixtral 8x7B"], blurb: "400B MoE, 17B active, 128 experts, early-fusion multimodal; sibling Scout claims 10M ctx.", tier: 1, from: 269 },
  { name: "π0.5", aliases: ["pi0.5", "pi 0.5", "pi-zero-point-five"], year: 2025, modality: ["Vision", "Language", "Control"], mechanism: "Self-attention", paradigm: "Diffusion", org: "Physical Intelligence", params: null, weights: "Open", parents: ["Gemma", "PaLM"], blurb: "Vision-language-action policy with a flow-matching action expert; cleans unseen homes.", tier: 1, from: 269 },
  { name: "Qwen3", aliases: ["Qwen3-235B-A22B"], year: 2025, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Alibaba", params: 235000, weights: "Open", parents: ["Qwen", "DeepSeek-R1"], blurb: "235B MoE, 22B active, 36T tokens, 119 languages, switchable thinking mode.", tier: 1, from: 269 },
  { name: "Claude 4", aliases: ["Claude Opus 4", "Claude Sonnet 4"], year: 2025, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "Anthropic", params: null, weights: "Closed", parents: ["Claude"], blurb: "Hybrid reasoning with tool use while thinking; Opus hit 72.5% on SWE-bench Verified.", tier: 1, from: 269 },
  { name: "Veo 3", aliases: ["Veo 3.1"], year: 2025, modality: ["Video", "Audio", "Language"], mechanism: "Self-attention", paradigm: "Diffusion", org: "Google DeepMind", params: null, weights: "Closed", parents: ["Imagen", "Sora"], blurb: "Latent-diffusion video that generates synced dialogue, SFX and ambience in one pass.", tier: 1, from: 269 },
  { name: "V-JEPA 2", aliases: ["VJEPA2", "V-JEPA"], year: 2025, modality: ["Video", "Control"], mechanism: "Self-attention", paradigm: "Masked modeling", org: "Meta AI", params: 1200, weights: "Open", parents: ["DINOv2", "MAE"], blurb: "1.2B ViT world model pretrained on 1M+ hours of video; zero-shot robot planning.", tier: 1, from: 269 },
  { name: "AlphaGenome", year: 2025, modality: ["Biology"], mechanism: "Hybrid", paradigm: "Supervised", org: "Google DeepMind", params: null, weights: "Partial", parents: ["AlphaFold 2", "ESM-2"], blurb: "Reads 1M DNA bases at single-base resolution; conv + transformer; wins 22 of 24 evals.", tier: 1, from: 269 },
  { name: "Grok 4", aliases: ["Grok 4 Heavy", "Grok"], year: 2025, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "xAI", params: null, weights: "Closed", parents: ["GPT-4", "DeepSeek-R1"], blurb: "RL at pretraining scale on the 200k-GPU Colossus cluster; 50.7% on Humanity's Last Exam.", tier: 1, from: 269 },
  { name: "Kimi K2", aliases: ["Kimi-K2", "Kimi K2.6", "Kimi"], year: 2025, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Moonshot AI", params: 1000000, weights: "Open", parents: ["DeepSeek-V3"], blurb: "1T MoE, 32B active, trained on 15.5T tokens with MuonClip and zero loss spikes.", tier: 1, from: 269 },
  { name: "Voxtral", aliases: ["Voxtral Small", "Voxtral Mini"], year: 2025, modality: ["Audio", "Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Mistral AI", params: 24000, weights: "Open", parents: ["Whisper", "Mistral 7B"], blurb: "24B speech-understanding LLM on Mistral Small 3; transcribes 30 min, beats Whisper v3.", tier: 1, from: 269 },
  { name: "Wan 2.2", aliases: ["Wan", "Wan 2.1", "Tongyi Wanxiang"], year: 2025, modality: ["Video", "Language", "Vision"], mechanism: "Self-attention", paradigm: "Diffusion", org: "Alibaba", params: 27000, weights: "Open", parents: ["DiT", "Sora"], blurb: "First open MoE video diffusion: 27B total, 14B active, high- and low-noise experts.", tier: 1, from: 269 },
  { name: "gpt-oss", aliases: ["gpt-oss-120b", "gpt-oss-20b"], year: 2025, modality: ["Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "OpenAI", params: 117000, weights: "Open", parents: ["GPT-3"], blurb: "117B MoE, 5.1B active, Apache 2.0, MXFP4 weights fit on a single 80GB GPU.", tier: 1, from: 269 },
  { name: "GPT-5", aliases: ["GPT-5 Thinking"], year: 2025, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "OpenAI", params: null, weights: "Closed", parents: ["GPT-4"], blurb: "Real-time router picks between a fast model and a deeper thinking model per request.", tier: 1, from: 269 },
  { name: "Genie 3", year: 2025, modality: ["Video", "Language", "Control"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Google DeepMind", params: null, weights: "Closed", parents: ["Veo 3"], blurb: "Text-to-playable world model: navigable 720p worlds at 24 fps, consistent for minutes.", tier: 1, from: 269 },
  { name: "Qwen-Image", aliases: ["Qwen-Image-Edit"], year: 2025, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Diffusion", org: "Alibaba", params: 20000, weights: "Open", parents: ["Stable Diffusion", "Qwen"], blurb: "20B MMDiT image generator famous for rendering dense English and Chinese text.", tier: 1, from: 269 },
  { name: "DINOv3", year: 2025, modality: ["Vision"], mechanism: "Self-attention", paradigm: "Self-distillation", org: "Meta AI", params: 7000, weights: "Open", parents: ["DINOv2"], blurb: "7B self-supervised ViT on 1.7B images; Gram anchoring keeps dense features sharp.", tier: 1, from: 269 },
  { name: "TRM", aliases: ["Tiny Recursive Model"], year: 2025, modality: ["Vision"], mechanism: "Recurrence", paradigm: "Supervised", org: "Samsung SAIT", params: 7, weights: "Open", parents: ["HRM"], blurb: "7M-param, 2-layer net that recursively refines its answer; 45% on ARC-AGI-1.", tier: 1, from: 269 },
  { name: "WeatherNext 2", aliases: ["FGN"], year: 2025, modality: ["Weather"], mechanism: "Graph message passing", paradigm: "Supervised", org: "Google DeepMind / Google Research", params: null, weights: "Closed", parents: ["GraphCast"], blurb: "Noise-injected graph transformer; hundreds of 15-day ensemble forecasts, 8x faster.", tier: 1, from: 269 },
  { name: "Gemini 3", aliases: ["Gemini 3 Pro", "Gemini 3.1 Pro", "Gemini 3 Deep Think"], year: 2025, modality: ["Vision", "Language", "Audio", "Video"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Google DeepMind", params: null, weights: "Closed", parents: ["Gemini"], blurb: "Sparse MoE, 1M context; debuted atop LMArena at 1501 Elo.", tier: 1, from: 269 },
  { name: "SAM 3", aliases: ["Segment Anything 3", "SAM 3.1"], year: 2025, modality: ["Vision", "Video", "Language"], mechanism: "Self-attention", paradigm: "Supervised", org: "Meta AI", params: 848, weights: "Open", parents: ["SAM", "CLIP"], blurb: "848M params; segments every instance of a noun phrase, trained on 4M+ unique concepts.", tier: 1, from: 269 },
  { name: "OLMo 3", aliases: ["Olmo 3", "Olmo 3-Think", "OLMo"], year: 2025, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "Allen Institute for AI", params: 32000, weights: "Open", parents: ["Llama 2", "Qwen3"], blurb: "Fully open 7B/32B: weights, ~6T-token Dolma 3 data, checkpoints and RLVR recipe.", tier: 1, from: 269 },
  { name: "Qwen3.5", aliases: ["Qwen3.5-397B-A17B"], year: 2026, modality: ["Vision", "Language", "Video"], mechanism: "Hybrid", paradigm: "Autoregressive", org: "Alibaba", params: 397000, weights: "Open", parents: ["Qwen3", "Mamba"], blurb: "397B MoE, 17B active; 3 Gated DeltaNet layers per attention layer; native multimodal.", tier: 1, from: 269 },
  { name: "DeepSeek-V4", aliases: ["DeepSeek-V4-Pro", "DeepSeek-V4-Flash"], year: 2026, modality: ["Language"], mechanism: "Self-attention", paradigm: "Autoregressive", org: "DeepSeek", params: 1600000, weights: "Open", parents: ["DeepSeek-V3", "Kimi K2"], blurb: "1.6T MoE, 49B active, compressed sparse attention, 1M context, 32T+ tokens, MIT.", tier: 1, from: 269 },
  { name: "Claude Mythos", aliases: ["Claude Mythos Preview", "Mythos"], year: 2026, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "Anthropic", params: null, weights: "Closed", parents: ["Claude 4"], blurb: "Gated cyber preview; autonomously found thousands of zero-days in major OSes and browsers.", tier: 1, from: 269 },
  { name: "GPT-6", aliases: ["GPT-6 Astra", "GPT-6 Sol", "GPT-6 Luna"], year: 2026, modality: ["Vision", "Language"], mechanism: "Self-attention", paradigm: "Reinforcement learning", org: "OpenAI", params: null, weights: "Closed", parents: ["GPT-5"], blurb: "First OpenAI model rated 'Critical' for cyber capability under its Preparedness Framework.", tier: 1, from: 269 },
];

export const NAME_INDEX: Map<string, Arch> = (() => {
  const m = new Map<string, Arch>();
  for (const a of ARCHITECTURES) {
    m.set(norm(a.name), a);
    for (const al of a.aliases ?? []) m.set(norm(al), a);
  }
  return m;
})();


export const ANSWER_POOL = ARCHITECTURES.filter((a) => a.tier === 1);
